Tg feature loginsignup
redacademy/wr-fall-2019 pull request #11
Opened 2019-12-03 23:32 UTC by greywall

# Feature Login Signup

- Folder Structure for login and signup.

2019-12-03 23:53 UTC, siddharthparmar7 requested changes
Please make the requested changes. Thank you.

2019-12-03 23:53 UTC, siddharthparmar7 commented on client/js/App.js
> +        {/* </StatusBar> */}
`StatusBar` is a self-closing tag. Remove the comments if not needed.

2019-12-03 23:53 UTC, siddharthparmar7 commented on client/js/components/AccountForm/AccountForm.js
> +      formToggle: true,
Create 2 screens, one for login and one for sign up. No need to toggle.

2019-12-03 23:53 UTC, siddharthparmar7 commented on client/js/components/AccountForm/AccountForm.js
> +        <Text>Password: ________</Text>
Use final-form lib to create the login and sign up form.

2019-12-03 23:53 UTC, siddharthparmar7 commented on client/js/screens/Login/Login.js
> +  return <AccountFrom />;
This component should just render the final form for Login.

2019-12-04 00:14 UTC, iyuvraajsingh approved these changes

2019-12-04 00:14 UTC, merged