Tg feature campaignconfirm
redacademy/wr-fall-2019 pull request #58
Opened 2019-12-13 04:01 UTC by greywall

# Add forward to confirm screen after user clicks subscribe

- Add logic for onpress forward
- Add logic for populating images on campaigns screen

2019-12-13 21:08 UTC, siddharthparmar7 requested changes
Please make the changes.

2019-12-13 21:08 UTC, siddharthparmar7 commented on client/js/components/MainSubscribeButton/MainSubscribeButton.js
> +                  console.log('hello');
remove console log.

2019-12-13 21:08 UTC, siddharthparmar7 commented on client/js/components/MainSubscribeButton/MainSubscribeButton.js
> +                      userid: 'ck3yzox88i13o0b00u0ak6b3h',
use a variable instead of static data.

2019-12-13 21:08 UTC, siddharthparmar7 commented on client/js/components/MainUnsubscribeButton/MainUnsubscribeButton.js
> +                      userid: 'ck3yzox88i13o0b00u0ak6b3h',
same as above

2019-12-13 21:08 UTC, siddharthparmar7 commented on client/js/screens/Campaigns/Campaigns.js
> +  console.log(pageName);
remove console logs.

2019-12-14 23:41 UTC, greywall commented on client/js/screens/Campaigns/Campaigns.js
> +  console.log(pageName);
Done

2019-12-14 23:42 UTC, greywall commented on client/js/components/MainSubscribeButton/MainSubscribeButton.js
> +                  console.log('hello');
Done

2019-12-14 23:45 UTC, greywall commented
Done. Ready to for review.

2019-12-16 18:58 UTC, siddharthparmar7 requested changes

2019-12-16 18:58 UTC, siddharthparmar7 commented on client/js/components/MainSubscribeButton/MainSubscribeButton.js
>    return (
Resolve your merge conflicts properly.

2019-12-16 23:03 UTC, greywall commented on client/js/components/MainSubscribeButton/MainSubscribeButton.js
>    return (
Done.

2019-12-16 23:05 UTC, greywall commented
Ready for review.

2019-12-16 23:10 UTC, siddharthparmar7 approved these changes

2019-12-16 23:10 UTC, merged