Tg feature onboardingasync
redacademy/wr-fall-2019 pull request #61
Opened 2019-12-13 20:35 UTC by greywall

# Create onboarding async

- Add touchable opacity to go from onboarding screen to login page
- Add async storage to track if onboarding has happened
- Add logic to not show onboarding if value is true

2019-12-13 22:55 UTC, siddharthparmar7 requested changes
delete .DS_Store file and yarn lock from the root of your project.

2019-12-13 22:55 UTC, siddharthparmar7 commented on yarn.lock
> +
delete this file.

2019-12-13 22:55 UTC, siddharthparmar7 commented
Also, please resolve merge conflicts.

2019-12-14 17:57 UTC, greywall commented on yarn.lock
> +
Done.

2019-12-14 23:50 UTC, greywall commented
The push for this pull request failed. Will need assistance in pushing on Monday.

2019-12-16 19:03 UTC, siddharthparmar7 requested changes

2019-12-16 19:03 UTC, siddharthparmar7 commented on client/js/components/MainSubscribeButton/MainSubscribeButton.js
> +                  console.log('hello');
remove this console log.

2019-12-16 19:03 UTC, siddharthparmar7 commented on client/js/screens/Onboarding/Onboarding.js
> +                  console.log(e);
remove this console log.

2019-12-16 23:15 UTC, siddharthparmar7 commented
Please resolve merge conflicts.

2019-12-16 23:30 UTC, greywall commented on client/js/screens/Onboarding/Onboarding.js
> +                  console.log(e);
Done.

2019-12-16 23:30 UTC, greywall commented on client/js/components/MainSubscribeButton/MainSubscribeButton.js
> +                  console.log('hello');
Done

2019-12-17 17:14 UTC, siddharthparmar7 requested changes
Please remove .DS_Store file from the root of your project.

2019-12-17 22:07 UTC, siddharthparmar7 approved these changes

2019-12-17 22:07 UTC, merged